# Generated by Django 3.0.5 on 2020-04-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('creator', models.CharField(max_length=32)),
                ('group_size', models.IntegerField()),
                ('build_cost_stone', models.IntegerField()),
                ('build_cost_frags', models.IntegerField()),
                ('build_cost_hqm', models.IntegerField()),
                ('build_cost_scrap', models.IntegerField()),
                ('upkeep_cost_stone', models.IntegerField()),
                ('upkeep_cost_frags', models.IntegerField()),
                ('upkeep_cost_hqm', models.IntegerField()),
                ('upkeep_cost_scrap', models.IntegerField()),
                ('raid_cost', models.IntegerField()),
                ('efficiency_score', models.FloatField()),
                ('feature_1', models.CharField(max_length=32)),
                ('feature_2', models.CharField(max_length=32)),
                ('feature_3', models.CharField(max_length=32)),
            ],
        ),
    ]
