# Generated by Django 3.0.5 on 2020-04-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='link',
            field=models.CharField(default='youtube.com', max_length=64),
            preserve_default=False,
        ),
    ]
