# Generated by Django 3.0.5 on 2020-05-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='fortify_link',
            field=models.CharField(default='N/A', max_length=32),
            preserve_default=False,
        ),
    ]
