# Generated by Django 3.0.5 on 2020-05-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_base_fortify_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_foreign', models.IntegerField(default=1)),
                ('account_foreign', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('content', models.CharField(max_length=512)),
            ],
        ),
    ]
